import Header from './Header'
import Footer from './Footer'
import Head from 'next/head'
import { Context as AuthContext } from '../../context/AuthContext';
import { useEffect, useContext } from 'react'
import { ToastContainer, Slide } from 'react-toastify';
import styles from '../../styles/Layout.module.scss'

export default function Layout({ children, brandName }) {
  const { state: { errorMessage }, getAuth } = useContext(AuthContext);
  
  useEffect(() => {
    getAuth();
  }, []);

  return (    
    <div className={styles.container}> 
      <Head>
        <title>Traverston</title>
        <meta name="description" content="Generated by create next app ok" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastContainer
        theme='light'
        position="top-right"
        transition={Slide}
        autoClose={3000}
        hideProgressBar={true}
        newestOnTop={false}
        closeOnClick
        rtl={false}
        pauseOnFocusLoss
        draggable
        pauseOnHover
        />
        {/* Same as */}
      {/* <ToastContainer /> */}
      <Header brandName={brandName} />

      <main className={styles.main}>{children}</main>

      <Footer />
    </div>
  )
}