import { useState, useEffect, useContext } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import { Context } from '../context/AuthContext';
import SigninForm from '../components/SigninForm';

export default function Signin() {
  const { state, signin } = useContext(Context);

  // const signIn = async () => {
  //   signin({
  //     email: 'lt@example.com',
  //     password: 'secret'
  //   });
  // };
  return (
    <div className={styles.container}>
      <Head>
        <title>Sign in</title>
        <meta name="description" content="Generated by create next app ok" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="row">
        <div className="col-6">
          <SigninForm 
            onSubmit={signin}
          />
        </div>
      </div>
      <p>
        token: {state.token}
      </p>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getServerSideProps = async () => {
  const req = await fetch(`${process.env.NEXT_PUBLIC_BASE_URL}/users`);
  const data = await req.json();
  // console.log(`the api base url is ${process.env.NEXT_PUBLIC_BASE_URL}`)
  // console.log('data', data)
  return {
    props: {
      outputProp: {
        name: data.name,
        code: data.code,
        test: 'test',
        another: 'huh'
      }
    }
  }
}