const users = require('./users/users.service.js');
const authUser = require('./auth-user/auth-user.service.js');
const userProfile = require('./user-profile/user-profile.service.js');
const userAccounts = require('./user-accounts/user-accounts.service.js');
const emails = require('./emails/emails.service.js');
const userAccountVerification = require('./user-account-verification/user-account-verification.service.js');
const products = require('./products/products.service.js');
const userCarts = require('./user-carts/user-carts.service.js');
const paymentIntents = require('./payment-intents/payment-intents.service.js');
const paymentWebhooks = require('./payment-webhooks/payment-webhooks.service.js');
const sales = require('./sales/sales.service.js');
const tenants = require('./tenants/tenants.service.js');
const tenantRegistration = require('./tenant-registration/tenant-registration.service.js');
const rooms = require('./rooms/rooms.service.js');
const tenantRooms = require('./tenant-rooms/tenant-rooms.service.js');
const tenantDetails = require('./tenant-details/tenant-details.service.js');
const fileAuth = require('./file-auth/file-auth.service.js');
const plans = require('./plans/plans.service.js');
const paddleWebhooks = require('./paddle-webhooks/paddle-webhooks.service.js');
const tenantPlans = require('./tenant-plans/tenant-plans.service.js');
const tenantUsers = require('./tenant-users/tenant-users.service.js');
const emailsSendinblue = require('./emails-sendinblue/emails-sendinblue.service.js');
const userInvites = require('./user-invites/user-invites.service.js');
const tenantUserInvites = require('./tenant-user-invites/tenant-user-invites.service.js');
const tenantUsage = require('./tenant-usage/tenant-usage.service.js');
// eslint-disable-next-line no-unused-vars
module.exports = function (app) {
  app.configure(users);
  app.configure(authUser);
  app.configure(userProfile);
  app.configure(userAccounts);
  app.configure(emails);
  app.configure(userAccountVerification);
  app.configure(products);
  app.configure(userCarts);
  app.configure(paymentIntents);
  app.configure(paymentWebhooks);
  app.configure(sales);
  app.configure(tenants);
  app.configure(tenantRegistration);
  app.configure(rooms);
  app.configure(tenantRooms);
  app.configure(tenantDetails);
  app.configure(fileAuth);
  app.configure(plans);
  app.configure(paddleWebhooks);
  app.configure(tenantPlans);
  app.configure(tenantUsers);
  app.configure(emailsSendinblue);
  app.configure(userInvites);
  app.configure(tenantUserInvites);
  app.configure(tenantUsage);
};
