import Navbar from './Navbar'
import Footer from './Footer'
import styles from '../styles/Layout.module.scss'

export default function Layout({ children }) {
  return (    
    <div className={styles.container}>
      <Head>
        <title>Sign in</title>
        <meta name="description" content="Generated by create next app ok" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>{children}</main>
      <Footer />
    </div>
  )
}